[package]
name = "shaderlang"
version = "0.1.0"
authors = ["Brett Lajzer <brett@brettlajzer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "^5.0"
nom_locate = "^1.0"